platform:'ios','10.0'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterIOS' do
  
install_all_flutter_pods(flutter_application_path)

pod 'MJRefresh', '~> 3.5.0'



end
